# Generated by Django 5.1.1 on 2024-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file_path',
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
